### DISCUSSION TITLE
Paperless App for iOS

### DISCUSSION THREAD

**Discussion by bignellrp** [bauerj/paperless_app#36] [General]
It says ios in the title but ios doesn't seem to be available yet. I love paperless so far. Such a great idea but I'm stuck using another iOS app for the scanning which isn't the greatest. Any ideas when this might be available. I would pay for the app if it was on Apple App Store. Someone must have a developer account that can help get this up and running?

**Comment by bauerj** [comment]
Hey,

yes, this is the right place to ask!

Indeed, the title is a bit misleading. While the app is (theoretically) compatible with iOS it is not available through the app store yet.

@rssfed23 and @qcasey have shown interest in working on it. I'm not quite sure about the progress, maybe they can talk about that here.

**Reply by tcurdt** [reply]
If I end up going for paperless (currently had to postpone further tests due to time constraints) I am also happy to help.
That said - I am not really a Flutter person. The developer account should not really be the problem.

Are there any existing Flutter CI/CD setups we could leverage for the builds?

**Reply by bauerj** [reply]
> Are there any existing Flutter CI/CD setups we could leverage for the builds?

With Github Actions this should be easy;

```
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build ios --release --no-codesign
```
