### DISCUSSION TITLE
App URL to access paperless

### DISCUSSION THREAD

**Discussion by joelang1699** [bauerj/paperless_app#53] [Q&A] [answered]
![20210915_033333](https://user-images.githubusercontent.com/13611738/133360989-21006a7c-92a1-423e-8f69-c8e524daac3e.jpg)
Hello

I have paperless hidden behind Organizr/Nginx so that I less a user is logged into Organizr they get a 401 error. Due to this the android app is blocked naturally however it possible on Nginx to pass through the request if the specific URL is known in the nginx config file, eg with sonar it's URL/sonar/API

 What is the URL that the app uses? I was lead to believe it's /static/?

See the lower block where it's states auth_request off.

**Comment by qcasey** [comment, marked as answer]
The app uses /api/

Paperless-ng also uses /static/ and /ws/ in the web frontend I believe.

**Reply by joelang1699** [reply]
Worked perfectly, thanks Quinn!

**Comment by carlyman** [comment]
I use Authelia, so trying to follow the above, I can login and see document list/names...but I cannot actually view or download anything.  I've tried the following:
```
- domain:
  - <my paperless domain>
  policy: bypass
  resources:
    - "^/api.*$"
```

and...
```
- domain:
  - <my paperless domain>
  policy: bypass
  resources:
    - "^/(api|ws|static).*$"
```

Anything obvious missing above?

**Reply by timaschew** [reply]
You could inverse the logic, only check 2FA for the login page:

```
access_control:
  default_policy: deny
  rules:
    - domain: paperless.YOURDOMAIN
      resources:
        - '^/accounts/login.*'
      policy: two_factor
    - domain: paperless.YOURDOMAIN
      policy: bypass
```
